LANGUAGE_SKILL_MAP: dict[str, str] = {
    "JavaScript": "JavaScript",
    "TypeScript": "TypeScript",
    "Python": "Python",
    "Java": "Java",
    "C++": "C++",
    "C": "C",
    "C#": "C#",
    "Go": "Go",
    "Rust": "Rust",
    "Ruby": "Ruby",
    "PHP": "PHP",
    "Swift": "Swift",
    "Kotlin": "Kotlin",
    "Dart": "Dart",
    "R": "R",
    "Scala": "Scala",
    "Shell": "Shell/Bash",
    "PowerShell": "PowerShell",
    "Lua": "Lua",
    "Perl": "Perl",
    "Haskell": "Haskell",
    "Elixir": "Elixir",
    "Clojure": "Clojure",
    "Objective-C": "Objective-C",
    "HTML": "HTML/CSS",
    "CSS": "HTML/CSS",
    "SCSS": "HTML/CSS",
    "Sass": "HTML/CSS",
    "Vue": "Vue.js",
    "Svelte": "Svelte",
    "Jupyter": "Data Science",
    "Jupyter Notebook": "Data Science",
    "HCL": "Terraform/IaC",
    "Dockerfile": "Docker",
    "Makefile": "DevOps",
}


FRAMEWORK_KEYWORDS: dict[str, list[str]] = {
    "React": ["react", "nextjs", "next.js", "gatsby", "create-react-app", "remix"],
    "Next.js": ["nextjs", "next.js", "next-app"],
    "Vue.js": ["vue", "vuejs", "nuxt", "nuxtjs"],
    "Angular": ["angular", "ng-", "ngrx"],
    "Svelte": ["svelte", "sveltekit"],
    "Node.js": ["node", "express", "fastify", "nestjs", "koa"],
    "Django": ["django"],
    "Flask": ["flask"],
    "FastAPI": ["fastapi", "fast-api"],
    "Spring Boot": ["spring", "springboot", "spring-boot"],
    "Rails": ["rails", "ruby-on-rails"],
    "Laravel": ["laravel"],
    "Docker": ["docker", "dockerfile", "containerize", "container"],
    "Kubernetes": ["kubernetes", "k8s", "helm"],
    "AWS": ["aws", "lambda", "s3", "dynamodb", "cloudformation"],
    "Firebase": ["firebase", "firestore"],
    "MongoDB": ["mongodb", "mongoose", "mongo"],
    "PostgreSQL": ["postgres", "postgresql", "pg"],
    "Redis": ["redis"],
    "GraphQL": ["graphql", "apollo", "hasura"],
    "TensorFlow": ["tensorflow", "tf-", "keras"],
    "PyTorch": ["pytorch", "torch"],
    "Machine Learning": ["ml", "machine-learning", "deep-learning", "neural"],
    "React Native": ["react-native", "reactnative", "expo"],
    "Flutter": ["flutter"],
    "Tailwind": ["tailwind", "tailwindcss"],
    "Three.js": ["threejs", "three.js", "3d", "webgl"],
}